libunwind:  # [linux]
  - 1.6  # [linux]
pin_run_as_build:  # [linux]
    libunwind:  # [linux]
      max_pin: x.x  # [linux]
#c_stdlib_version:           # [osx and x86_64]
#  - "10.14"                 # [osx and x86_64]
#MACOSX_SDK_VERSION:         # [osx and x86_64]
#  - "10.14"                 # [osx and x86_64]
